version: "3"

services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: 'demo-storage-mongo-db'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  api:
    container_name: 'demo-storage-api'
    build:
      context: .
    ports:
      - 5001:8000
    depends_on:
      - mongo-db
    volumes:
      - files:/usr/src/app/upload_files

volumes:
  mongo-data:
  files:
