version: '3'

services:
  front:
    build:
      context: ../
      dockerfile: ./docker/front.dockerfile
    container_name: 'demo-service-front'
    ports:
      - 1337:8000
    depends_on:
      - api
    networks:
     - demo-service-network

  api:
    build:
      context: ../
      dockerfile: ./docker/api.dockerfile
    container_name: 'demo-service-api'
    ports:
      - 5000:8000
    networks:
     - demo-service-network

networks:
  demo-service-network:
    driver: bridge
