name: Docker build of the front of the demo service

on:
  push:
    branches:
      - main
    paths:
      - 'demo-service/FrontInstagramLike/**'

jobs:
  docker-build:
    name: Docker build of the front of the demo service
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build only the front container using docker-compose
        run: docker-compose build front
        working-directory: ./demo-service/docker

      - name: Run docker containers
        run: docker-compose up -d
        working-directory: ./demo-service/docker