name: Docker build of the demo storage app

on:
  push:
    branches:
      - main
    paths:
      - 'demo-storage/**'

jobs:
  docker-build:
    name: Docker build of the demo storage app
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the container
        run: docker-compose build
        working-directory: ./demo-storage

      - name: Run docker containers
        run: docker-compose up -d
        working-directory: ./demo-storage